services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: phantom-database-do-user-17771144-0.k.db.ondigitalocean.com
      PMA_PORT: 25060
      PMA_USER: usama
      PMA_PASSWORD: AVNS_RApWLHUdemTgHwU5oS7
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: AVNS_RApWLHUdemTgHwU5oS7
      MYSQL_DATABASE: phantom
      MYSQL_USER: usama
      MYSQL_PASSWORD: AVNS_RApWLHUdemTgHwU5oS7
    ports:
      - "25060:3306"
